### ISSUE TITLE
The link to get the pretrained model isn't working

### ISSUE THREAD

**Issue by scjjb** [dalifreire/tumor_regions_segmentation#11]
Clicking the link to the pretrained model reaches a page saying "404. That’s an error. The requested URL was not found on this server. That’s all we know."

**Comment by dalifreire** [comment]
Hi @scjjb, the link was updated to 
* https://ufubr-my.sharepoint.com/:f:/g/personal/dalifreire_ufu_br/EuSw2gCeAxhIt0pWLYdid2MBgpEuC2QIXJz87u76sow_OA?e=T7jQgM

Let me know if everything is working now.
thanks
